### ISSUE TITLE
game playing with CNN

### ISSUE THREAD

**Issue by yuchenhou** [yuchenhou/elephant#10]
### Scenario: predict following moves in go
Given the game history
Predict the next k moves

### Implementation: CNN
The CNN reads a heavily hand engineered 19x19x25 D vector (with current, historical game situation and also the opponent information encoded) and predict next k future moves at the same time

### Highlights
9. k outputs generated concurrently instead of sequentially, useful for training, not predicting
9. no pooling layers
9. no weight constraint(no filter replications?)
9. the problem is substantially harder than similar image recognition problems (very high sensitivity)
9. 1st convolutional layer is not trained, but manually generated
9. no well defined input layer
9. history is handled in a very unique way
9. recurrent net didn't perform well
9. optional search engine
9. this paper has too many elements

### Questions
9. does the CNN treat next k moves as independent?
9. will it be better to use recurrent net to handle game history instead of hand-engineering a feature map?
9. will it be better to remove all hand engineered features?

**Comment by lbholder** [comment]
Might also be interested in this deep learning approach to playing arcade games:
http://www.nature.com/nature/journal/v518/n7540/full/nature14236.html
The same group at Google released Tensor Flow as a tool for this kind of work. Might be worth a look. See https://www.tensorflow.org/.

**Comment by yuchenhou** [comment]
Oh, this is reinforcement learning. That's interesting.
