### ISSUE TITLE
Data sets

### ISSUE THREAD

**Issue by lbholder** [yuchenhou/elephant#13]
In terms of datasets to use for testing, we already talked about IMDB and DBLP. These are also used in Yibo Yao's thesis, which I will email you, but here are links to some of his papers:

http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=7023382
http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=7363805

I also mentioned the Stanford SNAP repository, which is at http://snap.stanford.edu/data/index.html.

I also mentioned the collection of challenges at https://www.kaggle.com/. After a quick look, I didn't see any obvious graph/network specific challenges, but many of these datasets could be represented as graphs.

**Comment by yuchenhou** [comment]
Thanks! I'll take a look at them.

**Comment by yuchenhou** [comment]
How about this edge regression problem on kaggle: [Home Depot Product Search Relevance](https://www.kaggle.com/c/home-depot-product-search-relevance)? It's similar to Yibo's node classification problem for IMDB. A direct comparison is below:

category | IMDB | Home Depot
---|---|---
central node | movies | products and queries
side node | makers (e.g. director, actor, company etc) | companies/brands
edge | makers->movies | companies -> products, queries -> products
task | given a movie(node), predict its successful label | given a (query, product) pair(edge), predict its relevance level

**Comment by lbholder** [comment]
For Home Depot there isn't really any structure there, and most information would have to be extracted from natural language text. So, I don't think this is really a graph problem.

**Comment by lbholder** [comment]
Yahoo Music is more promising, because there is more structure (users rate songs, artists make songs, genre hierarchy). Similar to IMDB. In fact, if you combine IMDB with users' ratings of movies (e.g., Netflix data), then they are essentially equivalent.

**Comment by yuchenhou** [comment]
Cool! Then I'll think about the deep learning approach for the music rating prediction task. Later on I can generalize it to handle more complex scenario with user-user interactions, user activities, etc.

**Comment by yuchenhou** [comment]
The specific dataset I'd like to try out is the C15 of Yahoo Music. It has 4 parts, we can use the small part first. A brief summary is as follows.

All dataset:
============
#Users=5014136
#Items=1158226
#Ratings=1329499381
(#TrainRatings=1279358021, #ValidationRatings=20056544, #TestRatings=30084816)

Small.ltr dataset:
==================
#Users=249012
#Items=296111
#Ratings=62551438
(#TrainRatings=61944406,  #TestRatings=607032)

**Comment by yuchenhou** [comment]
This dataset is too big for my desktop. It takes forever for the training to finish. I'll try to find a smaller dataset to run tests on.

**Comment by yuchenhou** [comment]
I took a closer look at the results in the paper I was comparing against. I noticed their experiments are separated in a different domains(genres), which is not the same as the experiments I'm running. That might be a reason why their errors are smaller. I should compare my results with those from same experiments I'm running.

**Comment by yuchenhou** [comment]
This issue was replaced by #24 .
