### ISSUE TITLE
problem definition

### ISSUE THREAD

**Issue by yuchenhou** [yuchenhou/elephant#14]
## Graph features
I'm studying a specific type of graph which can represent a large number of real world networks. It has following features:

### every node represents 1 entity, with 1 attribute: type
Examples:

9. song1: node1.type = song
9. singer2: node2.type = singer
9. fan3:  node3.type = fan

### every edge represents 1 relation, with 2 attributes: type, value
Examples:

9.  fan3 rated 9 for song1: edge1 = (node3, node1); edge1.type = rate, edge1.value = 9;
9. singer2 performed song1: edge2 = (singer2, song1); edge2.type = perform, edge2.value = true;
9. singer9 didn't perform song1: edge9 = (singer9, song1); edge9.type = perform, edge9.value = false;
9. fan1 is a friend of fan 2: edge8 = (fan1, fan2); edge8.type = friendship, edge8.value = true;

### Scenario: edge prediction
Given such a graph and an edge with unknown value
Predict the unknown value
Examples:

9. how will fan3 rate song1: edge1 = (node3, node1); edge1.type = rate, edge1.value = ?
9. will fan1 be a friend of fan2: edge8 = (fan1, fan2); edge8.type = friendship, edge8.value = ?

**Comment by lbholder** [comment]
Sounds good, except for edge #3 (singer didn't perform song). This will cause your graph to become very dense, and therefore take more time to analyze.
