### ISSUE TITLE
Problem solution

### ISSUE THREAD

**Issue by yuchenhou** [yuchenhou/elephant#15]
## Idea
An ANN always need feedback in order to learn anything, so the learning needs to be(or converted to) supervised learning. For the problem defined in #14,  there are 2 goals.

### Type specific node nets encode nodes to node feature vectors
9. a type specific net encodes nodes of the same type to feature vectors in the type space: the singer net encodes all singers to singer feature vectors in singer space; the song net encodes all songs to song feature vectors in song space; (should nodes of different types be mapped to a shared space? as in #8 )
9. the feature vectors contain complete information about the nodes: cord, instrument, tempo, etc

### Type specific edge nets process node feature vectors to predict edge attributes
9. a type specific net processes the nodes to predict edge attributes of the same type: the rating net processes all (fan, song) pairs to predict ratings; the perform net processes all (artist, song) pairs to predict performance(true or false);

### learning
similar implementation as DSSM #16, supervised, one net for each type of nodes or edges:
word sequences -> nodes
relevance -> edge.value

### prediction
same as learning, except with unknown edges

## Highlights
The learning is online, naturally suitable for dynamic graph.

**Comment by lbholder** [comment]
Deep networks can also be used for feature generation, not just supervised learning. You essentially want the network to output the same thing that is input, but by going through some low-node-count layers. For example, you could use a network with 1000 pixel inputs, with a deep layer of say 10 nodes, and then an output layer of 1000 nodes. The feedback for learning is whether the outputs equal the inputs. Once a set of images a is learned, then the 10 internal nodes are essentially features describing the images. These feature can then be used for other tasks, including supervised learning, but also unsupervised learning.
