### ISSUE TITLE
rating prediction accuracy comparision

### ISSUE THREAD

**Issue by yuchenhou** [yuchenhou/elephant#24]
Here is a recent paper on rating prediction which we can compare with: [Efficient recommendation methods using category experts for a large dataset](http://www.sciencedirect.com/science/article/pii/S1566253515000706). The specific experiment in the paper I will do has the follwoing specs:

- dataset: [MovieLens 100k](http://grouplens.org/datasets/movielens/100k/)
- test set portion: 20%
- metric: MAE(mean absolute error)
- best result: MAE = 0.740

**Comment by yuchenhou** [comment]
OK, it made it. After more tweaking, our model can now consistently beat theirs: the testing MAE are in range [0.69, 0.72]. An example fit process is shown below:
![movie](https://cloud.githubusercontent.com/assets/8304443/13757490/f6b4f164-e9e1-11e5-9ec0-4c8becfb57db.png)

**Comment by yuchenhou** [comment]
Here is another paper we can compare with: [Expert Systems with Applications](http://www.sciencedirect.com/science/article/pii/S0957417415007897) . It's lowest MAE on MovieLen 1M dataset is ~0.79. Our estimator can get an MAE of 0.655. Below is the learning process:
![movie](https://cloud.githubusercontent.com/assets/8304443/14235963/b1338a5c-f9c1-11e5-9180-7d7d1875cd7f.png)

**Comment by yuchenhou** [comment]
[Expert Systems with Applications](http://www.sciencedirect.com/science/article/pii/S0957417415007897) has experiments on both MovieLens 100K and MovieLens 1M. So I think this paper is all we need as a reference for prediction accuracy. We don't need [Efficient recommendation methods using category experts for a large dataset](http://www.sciencedirect.com/science/article/pii/S1566253515000706) any more.

**Comment by lbholder** [comment]
We should compare against whichever approach has better performance.

**Comment by yuchenhou** [comment]
OK.

**Comment by yuchenhou** [comment]
This is the last issue in movie rating prediction, for which we have achieved good results. I'll close it now.
