### ISSUE TITLE
post recommendation

### ISSUE THREAD

**Issue by yuchenhou** [yuchenhou/elephant#25]
### background: social media

>  In terms of application areas, the growth of user-generated content on blogs, microblogs, discussion forums, product reviews, etc., has given rise to a host of new opportunities for graph mining in the analysis of social media. Social media analytics is a fertile ground for research at the intersection of mining graphs and text. As such, this year we especially encourage submissions on theory, methods, and applications focusing on the analysis of social media. - [MLG](http://www.mlgworkshop.org/2016/)
### motivation: users and texts

As MLG stresses the importance of social media, i.e., user generated texts, we can consider a feature expansion for our movie recommendation system: post recommendation. Basically, we have users nodes and posts nodes (texts), links can be read/write, like/dislike, comments (texts). These data allow us to learn the users' interests and recommend posts to them. Natural language processing will be useful for this feature.
### feature: post recommendation
- in order to recommend posts to users
- the estimator needs to predict how a user will read/like/comment a post

**Comment by lbholder** [comment]
I agree. This is a good application area for your work. And MLG is a good place to submit a paper if we can get one ready. Looks like they extended the deadline to May 27.

**Comment by yuchenhou** [comment]
Moving forward, we will still consider the attributes of nodes (for example, the text content of a post) as metadata so we will not give this direction further consideration.
