### ISSUE TITLE
time variant graph

### ISSUE THREAD

**Issue by yuchenhou** [yuchenhou/elephant#35]
While searching for data sets used in #34 , I noticed a time variant weighted graph - [a messaging network of students](https://toreopsahl.com/datasets/#online_social_network). The data is essentially a set of text messages recording when, who sent how much text to whom:

```
time source destination character#
"2004-04-21 20:07:46" 32 58 36
"2004-04-21 20:07:48" 12 66 199
"2004-04-21 20:11:54" 67 32 48
"2004-04-21 20:12:51" 41 32 39
...
...
```

I think an interesting graph model is that these records are samples of a time variant graph. The graph has a fixed number of nodes, but every link has a weight that is a function of time. In this view, each message is a sample of a link at a specific time. For example:

```
"2004-04-21 20:07:48" 12 66 35
"2004-04-22 20:07:48" 12 66 45
"2004-04-23 20:07:48" 12 66 55
"2004-04-24 20:07:48" 12 66 199
```

are 4 samples of the same link at 4 different times, indicating that this link is growing in weight. Another graph model is these are 4 links connecting the same node pair, but graph model is not able to incorporate time.

**Comment by lbholder** [comment]
Certainly can do edge-weight prediction on a static snapshot of the graph. Good also predict where the weights are headed in the future.

**Comment by yuchenhou** [comment]
This is an interesting direction but it is not aligned with our current direction.
