### ISSUE TITLE
gaze movement

### ISSUE THREAD

**Issue by yuchenhou** [yuchenhou/elephant#37]
### Observation on gaze movement
The process human understand an image is way more sophisticated than the typical process of image recognition with CNN: it is a gaze movement on the image. Interestingly, is very similar to a walk on a fully connected graph, where nodes are the regions with details, and the walk is the trace of the gaze. Presumably, gaze movement is guided by the brain with a goal to maximize information gain of the image. This observation provides some ideas on image/graph recognition with deep learning:

0. a model A can have a fixed resolution to look at a local region to gather local information, just like the eye collects details on a image
0. another model B can guide A to walk from one local region to another and remember all local information gathered by A, like the brain guides the eye
0. after some time, B gathers enough information to output whatever target it is trained to predict, like the brain can recognize the image's object, style, genre, etc.

Step 1 involves too much intelligence, probably some local search in a information space where the objective function needs to be learned through reinforcement learning. Maybe try something simple like random walk. Model B needs to be a RNN to remember things.

**Comment by lbholder** [comment]
Another challenge is that the network need access to the entire graph to find the "interesting" parts.
However, there are some ways to measure the information content of regions of a graph, for example, using entropy (how homogeneous the graph region is), or a likelihood measure (how does the region differ from the graph as a whole).

**Comment by yuchenhou** [comment]
Although this observation can be useful for designing a novel way to do graph attribute prediction, it is not very useful for link attribute prediction. We decided to focus on link attribute prediction so we will not continue this direction.
