### ISSUE TITLE
node vector semantics

### ISSUE THREAD

**Issue by yuchenhou** [yuchenhou/elephant#38]
## problem
The model can map each node to a node vector and use that vector to do prediction. However, we don't know the semantics of a node vector, i.e., we don't know the meaning of each item in a node vector. Consequently, we don't know what information about each node the model has gathered and how it uses that information to do prediction. If we can't get a deeper understanding on how the model works, it's hard to explain why this model can outperform non-deep learning models.

## observations
In [word2vec](https://www.tensorflow.org/tutorials/word2vec) technique, differences of word vectors can reveal word vector semantics, e.g., verb tense.

## approach
Use node vector differences to reveal node vector semantics, e.g., node distance.

**Comment by yuchenhou** [comment]
@lbholder I find it rather difficult to work with movie genre to reveal linear semantic relationship because the relation between the location of a movie point in the embedding space and the genre of the movie is very vague. Below is an example of movie embedding:
![screenshot from 2017-06-22 16-27-04](https://user-images.githubusercontent.com/8304443/27460594-bb5d1d66-5769-11e7-98a7-bfb1007e9a07.png)
In this embedding space, movies points are colored by its `drama` label: drama movies are colored as orange and non-drama movies are colored as blue. I guess there is no direct way to do something like 

`drama = drama+sci-fi - sci-fi = drama+adventure - adventure`

There isn't such a vector like `drama` in this embedding space.


I think this linear relation verification approach worked in word embedding because words are essentially concepts. So word space is a concept space and concept_1 - concept_2 can be some other concept. For example: 

`power = king - man = queen - woman`.

But this doesn't quite work in our movie space. Movies with the same genre are all over the place. I think the reason is the embedding reflex the personal preferences of the movies, which is not related to the genres directly. For example, I like rate many drama movies 5 and many drama movies 1.

**Comment by yuchenhou** [comment]
I mean I can give rating 5 to many drama movies I like, and then rating 1 to many drama movies I don't like. So these movies are not even close in the embedding space.

**Comment by yuchenhou** [comment]
![screenshot from 2017-06-23 12-25-42](https://user-images.githubusercontent.com/8304443/27497454-933eb7e4-580f-11e7-928c-6e84030d5ad3.png)
This is the user embedding colored by gender: males users have blue color and female users have orange color. We can see users of 2 genders are scattered fairly evenly in the embedding space. I think this implies the metadata don't need to have any direct relation to the embedding semantics. Specifically, 2 users from different genders can be similar in their preferences for movies and close to each other in the embedding space.

**Comment by lbholder** [comment]
Might try a 2d projection to make it more obvious if a clear partitioning exists. The look of the 3d projection depends a lot on the particular angle of view.

**Comment by lbholder** [comment]
For the movies, would it be possible to look for relationships between individual movies? For example, check if distance(star_wars_1, star_wars_2) < distance(star_wars_1, youve_got_mail), i.e., a movie is closer to its sequel than to another movie.

**Comment by yuchenhou** [comment]
Will pick a few movie clusters and attempt to discover similarities for all the movies within each movie cluster.

**Comment by yuchenhou** [comment]
We settled down with distance measures for the movies and countries.

**Comment by alanyuchenhou** [comment]
This embedding shows the overall distribution of entities where similar entities are closer in the embedding space. Similar entities are the entities exhibiting similar interactions with other entities.

## movie embeddings
![movies-annotation](https://user-images.githubusercontent.com/8304443/33800963-4741d430-dd01-11e7-948c-4a1eb40a3980.png)
The embeddings of all movies in MovieLens100K dataset (where interactions are ratings users give to movies measured by the amount of stars in the rating):
“The Empire Strikes Back” is the
reference movie, shown as a red node with bold font name. “Raiders of the Lost Ark” is the closest
movie to the reference movie, shown as a purple node with purple name. 

## country embeddings
![countries-annotation-1](https://user-images.githubusercontent.com/8304443/33800967-5fda2f7e-dd01-11e7-81bf-98e33ac8417c.png)
The embeddings of countries in Collaboration dataset (where interactions are the collaborations between countries on research measured by the amount of publications):
The United States is the reference country,
shown as a red node with bold font name. China is the closest country to the reference country, shown as a purple node with purple name.
