### ISSUE TITLE
automata

### ISSUE THREAD

**Issue by yuchenhou** [yuchenhou/elephant#4]
There are some theoretical relations between a graph and a language:
a finite automaton accepts a regular language;
a push-down automaton accepts a context free language;

**Comment by lbholder** [comment]
Sounds good.

**Comment by yuchenhou** [comment]
There are very little automaton theory related work in deep learning. Maybe It's because the non-determinism in automata is too hard to work with. Context free grammar is mentioned in #9 : but the recursive neural net used there is not a popular neural net either.
