### ISSUE TITLE
GEM

### ISSUE THREAD

**Issue by yuchenhou** [yuchenhou/elephant#45]
Found a package that implements a few graph and node embedding methods:
https://github.com/palash1992/GEM

**Comment by yuchenhou** [comment]
The old model R implementation used many deprecated tensorflow modules so I did a rewrite. The new implementation has better performance in forum data set:
![link-weight-errors](https://user-images.githubusercontent.com/8304443/30038490-1459ed64-917a-11e7-96f1-bdaa5efbf2c6.png)
 However, the performance gain is not significant enough to make a point like "Model R outperforms node2vec in all scenarios".

**Comment by lbholder** [comment]
True. But looks like Model R should be preferred to node2vec. Model R probably significantly outperforms node2vec in Collaboration graph. And Model R does not worse than node2vec on all domains.

**Comment by yuchenhou** [comment]
I adopted LLE from all GEM approaches.
