### ISSUE TITLE
speech recognition with RNN

### ISSUE THREAD

**Issue by yuchenhou** [yuchenhou/elephant#5]
### Scenario: recognize an utterance
Given a spectrogram sequence (a vector sequence)
Predict the character sequence (the English sentence)

### Implementation: RNN (recurrent neural net)
The RNN reads the spectrogram sequence through a sliding window of size 11, and predicts the English character(can be space or blank) represented by the middle spectrogram in the window. The window slides from begin to end with a certain stride.

### Highlights:
 1. sequence of vectors as input and output: similar to NLP tasks, the input is not 1 vector, but a sequence of strongly related vectors.
 1. context assistance: similar to NLP implementations, the RNN takes the context of the spectrogram (a window of 11 spectrograms) into account when doing prediction
 1. sequence alignment: the input sequence of spectrograms (long) is aligned with the output sequence of characters (short) by filling blanks into the output sequence

### Questions:
 1. the RNN itself has the capability of "remembering" the input history using its feedback; how does this capability affects the context assistance?

**Comment by lbholder** [comment]
For graphs, could the sequence of vectors could represent properties of nodes, edges or small subgraphs. Not sure what the output would be. Maybe an attribute of the node/edge/subgraph.

**Comment by yuchenhou** [comment]
I think I can get more ideas about what to predict if I look more into #1 .
