### ISSUE TITLE
recommendation systems with CNN

### ISSUE THREAD

**Issue by yuchenhou** [yuchenhou/elephant#8]
### Scenario: item recommendation
Given user A and item B
Predict how much A likes B

### Scenario: [collaboration recommendation](https://aminer.org/billboard/collaboration)
Given an author
Predict his collaboration author in a different domain

### Implementation (some type of feed-forward neural net, not specified)
Every user, news, app, movie is represented by a vector in the corresponding space, the representation requires minimum processing from raw data. Every input vector has a separate net to handle but the user net feed to the output of every other net. The outcome is not only the result "like" or "not like", but the semantic vector representation for users and items.

### Highlights
- lightly processed features, not heavily processed or raw
- heavy feature dimension reduction process
- training data reduction: for each user, for each item type, average reduce all items (bad idea?)
- separate representations: users, news, apps, movies are represented in separate spaces
- the user net is always engaged; other nets are not

### Question
- user-user and item-item relation is not used; is this similar to word to vector problem?
- should users, user activities and items exist in the same space, as in natural language processing?
- as users' interests change in time, how should users' vectors change?
- how to define a user based on all kinds of online activities?
- 3 kinds of relations: user-user, user-item, item-item are not taken into account?

**Comment by yuchenhou** [comment]
### Paper: [Deep content-based music recommendation](http://papers.nips.cc/paper/5004-deep-content-based-music-recommendation)

### Scenario: music recommendation
Given a song (a spectrogram vector)
Predict its latent factors (feature vector) and recommendation rating, tags

### Implementation: CNN
The CNN reads the spectrogram vectors of songs and learn to predict its vector of latent factors, e.g. mood, theme, instrumentation, genre, etc. The learning is supervised by vectors produced from a user ratings processing system called weighted matrix factorization.

### Highlights
- tag prediction is done by logistic regression
- attribute based rating is better when relational data is rare
- relation based rating is better when relational data is adequate

### Questions
- how do we combine the power of attribute based rating and relation based rating?

**Comment by lbholder** [comment]
What do you mean by "relational data" and "relation based rating"? I didn't see these terms mentioned in the paper.
